### PR TITLE
Add dune and autogenerated opam file

### LINKED ISSUE #8: Opam package
Make QuantumLib into an opam package. Useful links:
* https://opam.ocaml.org/doc/Packaging.html
* https://coq.inria.fr/opam-packaging.html

### PR DESCRIPTION
**Pull request by k4rtik**
Other possibilities/considerations:
- ~~we could consider deleting the Makefile if everyone is happy with using dune~~ (made it a wrapper for dune)
- I was not sure what to fill in the maintainer and author fields, so currently they reference inQWIRE
- description can be better
- add a version such as v8.13.0 (since the library is most compatible with that version of Coq)

Closes #8

### CODE REVIEW

**Comment by k4rtik** [comment]
I am not sure I understood your point about the version causing a problem. If we are not explicit about it, we are using the commit hash as a version by default. Things could break with any new commit for a user of this library in the way you describe. Explicit versioning gives a bit more confidence and some static points in the commit history where users can expect things to not break with a version of Coq.

> Do you know if and how well it will work to use a dune Coq project as a library for a Coq project built on the classic CoqMakefiles?

That's a great question!

Since we have an opam package with this PR, it is similar to doing an `opam install <packagename>` and having the QuantumLib namespace available in your project. One does not need a `git submodule` for QuantumLib then. (Aside, once we are happy with this PR, we can consider submitting to the [opam-coq-archive](https://github.com/coq/opam-coq-archive) to make the process even smoother.)

Here's the output from my local testing (not `dev` is the default version for opam when we do not assign it explicitly and build a package from source):

```
~/Hub/inQWIRE/QuantumLib dune
❯ opam pin . # installing local package from my branch from this PR
Package QuantumLib does not exist, create as a NEW package? [Y/n] y
QuantumLib is now pinned to git+file:///Users/kartik/Hub/inQWIRE/QuantumLib#dune (version ~dev)

The following actions will be performed:
  ∗ install QuantumLib ~dev*
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
⬇ retrieved QuantumLib.~dev  (no changes)
∗ installed QuantumLib.~dev
Done.
~/Hub/inQWIRE/QuantumLib dune 5m 26s

[...]

~/Hub/inQWIRE/SQIR quantumlib*
❯ git status # Here I have removed the submodule for quantumlib
On branch quantumlib
Your branch is up to date with 'origin/quantumlib'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .gitmodules
	deleted:    externals/QuantumLib

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   _CoqProject                      # stripped externals/QuantumLib/* targets

~/Hub/inQWIRE/SQIR quantumlib*
❯ opam list | grep Quantum # the installed package from the local repo
QuantumLib                ~dev            pinned to version ~dev at git+file:///Users/kartik/Hub/inQWIRE/QuantumLib#dune
~/Hub/inQWIRE/SQIR quantumlib*
❯ make # compile at least one file that depends on QuantumLib, here SQIR/UnitarySem.v, stripped some initial warnings
git submodule init
git submodule update
coq_makefile -f _CoqProject -o CoqMakefile
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory -f CoqMakefile
COQC SQIR/UnitarySem.v
Crunching:
((fun x y : nat =>
  match x with
  | 0 =>
      match y with
      | 0 => cos (θ / 2)
      | 1 => - Cexp (PI / 2) * sin (θ / 2)
      | S (S _) => 0%R
      end
  | 1 =>
      match y with
      | 0 => Cexp (- (PI / 2)) * sin (θ / 2)
      | 1 => Cexp (- (PI / 2) + PI / 2) * cos (θ / 2)
      | S (S _) => 0%R
      end
  | S (S _) => 0%R
  end) =
 (fun x y : nat =>
  match x with
  | 0 =>
      match y with
      | 0 => cos (θ / 2)
      | 1 => - Cexp (PI / 2) * sin (θ / 2)
      | S (S _) => 0%R
      end
  | 1 =>
      match y with
      | 0 => Cexp (3 * PI / 2) * sin (θ / 2)
      | 1 => Cexp (3 * PI / 2 + PI / 2) * cos (θ / 2)
      | S (S _) => 0%R
      end
  | S (S _) => 0%R
  end))
Crunching: (hadamard × hadamard ⊗ I 2 = I 4)
Crunching: (∣1⟩⟨1∣ ⊗ σx .+ ∣0⟩⟨0∣ ⊗ I 2 = cnot)
COQC SQIR/UnitaryOps.v  # UnitarySem is built by now

[...]

❯ rg QuantumLib # we confirm that UnitarySem depends on QuantumLib
SQIR/UnitarySem.v
2:Require Import QuantumLib.Pad.
3:Require Export QuantumLib.Proportional.
```

**Comment by k4rtik** [comment]
What I would like reviewers to check is whether switching to this branch and doing interactive development works as expected. Currently, there is limited support for dune-based builds in various IDEs. But with the `_CoqProject` hack, as I have done here, it should work in both PG and VSCoq. But I would like you to test your personal setups to be sure.

**Comment by khieta** [comment]
Hi @k4rtik, I can confirm that running `make` and `opam pin .` works on my machine. (My set up is just the command line + emacs.)

I agree we should add a version number. Rather than 8.13.0, I'd prefer 1.0 (since this is the first version of QuantumLib) or 8.12.0 (since that's the oldest version of Coq that QuantumLib supports). Once you add a version number I'll merge this PR into main.

Before we submit to [opam-coq-archive](https://github.com/coq/opam-coq-archive) I'd like to move over the [Run.v](https://github.com/inQWIRE/SQIR/blob/quantumlib/SQIR/Run.v) file from SQIR & overhaul our documentation. I'm hoping that I'll be able to use [coqdoc](https://coq.inria.fr/refman/using/tools/coqdoc.html). I notice that your .opam file depends on `odoc` -- are we using that anywhere?

**Comment by k4rtik** [comment]
Alright, I am adding `v1.0.0` (using semantic versioning).

> I notice that your .opam file depends on `odoc` -- are we using that anywhere?

The opam file is autogenerated, but to clarify, `with-doc` is a filter so the dependency is required only if we were building documentation using a command like `dune build @doc`.

Indeed, documentation is a requirement before being accepted in the opam-coq-archive, so we will need to wait until documentation is ready.

We also need to use the `coq-XXX` name for the package for inclusion, so I am renaming the package in the next commit.

**Review by khieta — APPROVED** [review]
Looks good to me.

**Comment by adrianleh** [comment]
I see now what you mean by versioning - I got confused by using Coq's version numbers. Anyway, I'm very much in support of semantic versioning and maybe we can even eclipse Coq by not introducing breaking changes every couple versions ;)

**Review by adrianleh — APPROVED** [review]

**Pull request merged**
