### PR TITLE
Bumped to version 1.2.0

### PR DESCRIPTION
**Pull request by caldwellb**

### CODE REVIEW

**Review by adrianleh — APPROVED** [review]
Makes sense to me. However, having the `.opam` file which is generated from the dune project looks like tech debt to me

**Comment by k4rtik** [comment]
> having the `.opam` file which is generated from the dune project looks like tech debt to me

I believe I had to include it because the CI required it, see https://github.com/coq-community/docker-coq-action/blob/master/README.md#opam If there is a way to autogenerate it during the CI run, it will certainly be nice.

**Comment by adrianleh** [comment]
@caldwellb is currently working on fixing that. We filed an issue and got a response on how to hopefully make that work

**Comment by k4rtik** [comment]
I see https://github.com/coq-community/docker-coq-action/issues/83 is what you are referring to. I find it helpful to cross-link for context.

**Pull request merged**
