### PR TITLE
Update `ocaml_version` for coq:dev CI to run. Closes #23

### LINKED ISSUE #23: Dev CI compilation fails, despite code compiling everywhere else
When compiling the dev version of the project, an error is thrown near the beginning of compilation when trying to "pull docker image." Despite this fail, all other versions compile successfully. I also tried recompiling code that succeeded on dev 10 days ago, and the compilation failed, suggesting that the problem is external to the project. How should I fix this?

### PR DESCRIPTION
**Pull request by k4rtik**

### CODE REVIEW

**Comment by k4rtik** [comment]
So it seems that `8.12` image is not available with `4.12-flambda` and `dev` is not available with `4.07-flambda`. To obtain clean CI run, we should consider dropping `8.12`, which is almost two years old now. Generally, they provide support for "The last two compatible OCaml versions", see https://github.com/coq-community/docker-coq/wiki#supported-tags

@khieta thoughts? I am making this change to let the CI run.

**Comment by k4rtik** [comment]
If this change feels good, please feel free to merge.

**Comment by k4rtik** [comment]
@khieta clearly not, since `dev` doesn't have those images anymore. It also doesn't make sense in the long-term as Coq will ultimately drop support for older OCaml versions (though currently, the `minimum` version is 4.05, which is unoptimized and slower). The wiki page was last updated on Dec 9, 2021.

**Comment by k4rtik** [comment]
I made a post at https://coq.discourse.group/t/install-notes-on-ocaml-versions-and-coq-configuration/713/21?u=kartik so that someone provides updated guidance on which version to use.

**Comment by k4rtik** [comment]
It should be possible, but I was not able to figure it out last night. I will wait for some response to my post on Coq Discourse.

**Comment by khieta** [comment]
@k4rtik I merged your original PR this morning, but found that it didn't build. I guess they switched from 4.12-flambda to 4.13-flambda. My latest PR works, but I'd like to see if I can figure out how to run different versions of OCaml for different versions of Coq. It looks like they don't guarantee that 4.13-flambda will work in the future for Coq versions < 8.16.

**Pull request merged**
