### PR TITLE
Refactored and added proofs of QR decomposition and Schur decomposition

### PR DESCRIPTION
**Pull request by jakezweifler**
Hello! I wanted to push some of the changes I made last year in the stab-types branch. The changes are as follows: 

1. I split up Matrix.v into three different files, Matrix.v, RowColOps.v, and CauchySchwarz.v: 

- I found that the matrix modification defs and lemmas deserved their own file, hence, I created RowColOps.v. In this, I added more matrix operations and also unified some of the definitions. For example, I changed `get_vec` to `get_col` and `reduce` to `get_minor`. I also removed `xxx_append` since `xxx_wedge` is just the more general form, so redundancy in lemmas is reduced. In general, things are now more uniform and organized. This refactoring change is the most likely change here to cause trouble (depending on if other projects actually use any of the RowColOps.v lemmas).
- I created CauchySchwarz.v since these are the only lemmas/theorems in Matrix.v that cannot be generalized to an arbitrary ring. Thus, perhaps they deserve their own file.  

2. With the above machinery, I was able to give better proofs in VecSet.v and EigenVectors.v. In particular, I defined the adjugate of a matrix, which allows us to give an explicit definition for the inverse of a matrix, called `Minverse`. In Eigenvectors.v, instead of long, messy, proofs, I just proved that QR decomposition exists for linearly independent matrices and then I proved that every matrix has a Schur decomposition. From these, we get the generalized spectral theorem for free. Moreover, these matrix factorizations are useful in their own right so it is nice they could be added to the main branch. 
 
To fix any errors the update may cause: As mentioned, most errors, if any, will be caused by the refactoring described in 1. 

- If you use any lemmas involving inner-products, norm, or Cauchy Schwarz, you will need to import `CauchySchwarz.v` instead of just `Matrix.v`. Similarly, if you use any matrix operations (e.g. `col_swap`, `col_wedge`, etc...) you will need to import `RowColOps.v`. 

- Also, if you will need to change the names of `get_vec` and  `reduce` to `get_col` and `get_minor`. Moreover, the order of arguments of `get_col`  and `get_row` were changed to be more like the rest of the operations. Another change is that I made some of the lemmas more general, namely, proving them for `Matrix m n`'s instead of just `Square n`'s. Thus, some calls to these lemmas where the dimensions are explicit will need to be altered. It would be easiest to look in `RowColOps.v` or to use the Search function to see if any changes have occurred with the functions you are working with. 

- Finally, there is a chance the scoping may have been changed slightly. For example, `<` is overloaded for both reals and nats, so the local scope may be different depending on which files one imports. Usually, `nat` is preferred but in `CauchySchwarz.v`, various lemmas use real inequalities so the local scope was changed. I think this is unlikely to cause any problems, but figured I'd mention it just in case. Regardless, to fix, either change the local scope near the location of errors or make it explicit which `<` you are using, for example, write `... -> (x < y)%nat -> ...`.   

In general, I suspect these changes won't affect most users since these files are mostly used for the linear algebra leading up to quantum computing and not as much in the quantum computing theory itself. Regardless, if any issues cannot be quickly solved, feel free to make an issue report and we can try to help as best as possible.

### CODE REVIEW

**Comment by adrianleh** [comment]
I think it's reasonable to make a release of this. @jakezweifler can you bump the version in `dune-project` and the `.opam` file to 1.4.0?

We should also note if there are any changes that break backwards compatibility.

**Comment by rnrand** [comment]
Does Hermitian need to include WF_Matrix? Seems like it would be easier to just include the property of being self-adjoint (though I guess some lemmas would require well-formedness). We could then change the `_sa` lemmas to `_hermitian` lemmas. 

(WF_Unitary could also drop the WF_Matrix condition, but it would be work to stop that from breaking things.) 

Also, the "braqubit" lemmas should be braket lemmas – that was an ugly outcome of a naive search and replace.

**Comment by adrianleh** [comment]
I think we should keep the old `_sa` names as aliases to not break backwards compatibility

**Comment by rnrand** [comment]
I was thinking we could do that in the meantime.

I'd add deprecate warnings as well, eg.:

```
#[deprecated(note="Use hadamard_hermitian instead")]
Notation hadamard_sa := hadamard_hermitian (only parsing).
```

**Comment by adrianleh** [comment]
Just added that to my original comment. Would also do that with the other renaming we had @jakezweifler

**Comment by rnrand** [comment]
Also, declaring Hermitian transparent should allow us to use it to rewrite. (Otherwise I'm not sure.)

**Comment by jakezweifler** [comment]
@rnrand @adrianleh Just pushed fixes to the above issues. Let me know if there is anything else I should add/fix.

**Comment by adrianleh** [comment]
@jakezweifler Did you validate that old lemma names still work? Further I see some Notation wrappers are not marked as parsing only, specifically `get_vec`, `reduce`, `col_append`, `row_append`. Also I assume `row_append'` exists because of implicit parameters. Is it possible to avoid that?

**Comment by jakezweifler** [comment]
@adrianleh Yes, I ran tests, and the notation substitutions work surprisingly well, even with autorewrites. 

As for col_wedge', indeed the implicit parameters meant I either had to make an extra variable name or exclude the depreciation warning. For some reason, Coq does not give a way to add a deprecation warning before a definition, only before notation. I ended up just adding back other lemmas having to do with the append functions, although gave these some warnings.

I also ran tests

**Review by adrianleh — APPROVED** [review]

**Comment by adrianleh** [comment]
@rnrand unless there are objections, I'd be happy to merge

**Comment by rnrand** [comment]
Looks good to me.

**Comment by adrianleh** [comment]
Submitted to opam: https://github.com/coq/opam/pull/2995

**Comment by jakezweifler** [comment]
@adrianleh @rnrand Great, thanks for the help! Let me know if there are any breaks and I will try to fix.

**Pull request merged**
